models:
  - name: dim_listings_cleaned
    columns: 

    - name: listing_id
      tests:
        - unique
        - not_null 

    - name: host_id
      test:
        - not_null
        - relationships:
            to: ref('dim_hosts_cleaned')
            field: host_id

    - name: room_type
      test:
        - accepted_values:
            value: ['Entire home/apt',
                    'Private room',
                    'Shared room',
                    'Hotel room']